import type { Metadata } from "next";
import "@/app/[locale]/globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { Toaster } from "@/components/ui/sonner";
import "@fontsource/inter/400.css";
import "@fontsource/inter/700.css";
import localFont from "next/font/local";

const inter = localFont({
	src: [
		{
			path: "./fonts/Inter-Regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/Inter-Bold.woff2",
			weight: "700",
			style: "normal",
		},
	],
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;
	if (!routing.locales.includes(locale as never)) {
		notFound();
	}
	const messages = await getMessages();
	setRequestLocale(locale);

	return (
		<html lang={locale}>
			<body className={`${inter.variable} antialiased m-[0px] p-0`}>
				<NextIntlClientProvider messages={messages}>
					{children}
					<Toaster />
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
