import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/[locale]/globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const inter = Inter({
	weight: ["400", "500", "600", "700"],
	variable: "--font-inter",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const messages = await getMessages();

	return (
		<NextIntlClientProvider messages={messages}>
			<html lang="en">
				<body className={`${inter.variable} antialiased m-[0px] p-0`}>
					{children}
				</body>
			</html>
		</NextIntlClientProvider>
	);
}
