import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/[locale]/globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
	weight: ["400", "500", "600", "700"],
	variable: "--font-inter",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;
	if (!routing.locales.includes(locale as never)) {
		notFound();
	}
	const messages = await getMessages();
	setRequestLocale(locale);

	return (
		<html lang={locale}>
			<body className={`${inter.variable} antialiased m-[0px] p-0`}>
				<NextIntlClientProvider messages={messages}>
					{children}
					<Toaster />
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
